---
- name: Updating server using 'apt update'
  apt:
    state: latest
    upgrade: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Installing some necessary packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items: 
    - wget
    - vim
    - ufw
    - telnet
    - gcc
    - openssl
    - make

- name: Allowing SSH service in ufw firewall
  ufw: 
    rule: allow
    port: 22

- name: Enabling Logging in ufw firewall service
  ufw: 
    logging: on

- name: Starting ufw firewall service
  ufw: 
    state: enabled
    policy: reject

- name: Restarting Machine
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  become: true
  ignore_errors: true
  tags: reboot

- name: Waiting for server to reboot and come back
  wait_for: 
    host: "{{ inventory_hostname }}"
    state: started 
    delay: 15 
    timeout: 30
  delegate_to: localhost
  become: false
  tags: reboot
