---
- block:
    - name: Updating server using 'yum update'
      yum:
        name: "*"
        state: latest
        update_cache: yes
        exclude: 
          npm
          nodejs
      tags: 
        - server_update
        - yum_update
      register: server_update
    
    - name: Installing some necessary packages
      yum:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items: "{{ redhat.packages }}"
      tags: basic_packages
    
    - name: Setting Up Selinux
      selinux:
        state: "{{ redhat.selinux.state }}"
        policy: "{{ redhat.selinux.policy }}"
      tags: selinux

    - name: Starting firewalld service
      systemd: 
        name: firewalld
        state: started
        enabled: yes
      tags: firewall
    
    - name: Allowing custom ssh firewalld port
      firewalld: 
        port: '{{ custom_ssh_port }}/tcp'
        permanent: true
        state: enabled
      tags: firewall
      notify: restart firewalld

    - name: Allowing http firewalld service
      firewalld: 
        service: http
        permanent: true
        state: enabled
      tags: firewall
      notify: restart firewalld
    
    - name: Restarting Machine
      shell: sleep 2 && shutdown -r now "Ansible updates triggered"
      async: 1
      poll: 0
      become: true
      ignore_errors: true
      tags: 
        - reboot
        - server_reboot
      when: server_update.changed
      register: server_reboot
    
    - name: Waiting for server to reboot and come back
      wait_for: 
        host: "{{ inventory_hostname }}"
        state: started 
        delay: 15 
        timeout: 60
      delegate_to: localhost
      become: false
      tags: reboot
      when: server_reboot.changed
