---
- hosts: webservers
  tasks:
  - name: Aapache Installation on Redhat Family OS
    yum: name=httpd state=latest
    when: ansible_os_family == "CentOS"

  - name: Aapache Installation on Debian Family OS
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: write the apache config file
    template: src=httpd.j2 dest=/etc/httpd.conf
    when: ansible_os_family == "CentOS"
    notify:
    - restart apache on RedHat OS

  - name: write the apache config file
    template: src=httpd.j2 dest=/etc/apache2/apache2.conf
    when: ansible_os_family == "Debian"
    notify:
    - restart apache on Debian OS

  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
    when: ansible_os_family == "CentOS"

  - name: ensure apache is running (and enable it at boot)
    service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"

  handlers:
    - name: restart apache on RedHat OS
      service: name=httpd state=restarted

    - name: restart apache on Debian OS
      service: name=apache2 state=restarted
