---
# defaults file for roles/base
custom_ssh_port: 33433
redhat:
  packages:
    - wget
    - vim
    - net-tools
    - firewalld
    - telnet
    - yum-utils
    - gcc
    - openssl-devel
    - gcc-c++
    - make
    - atop

  selinux: 
    state: enforcing
    policy: targeted
  
debian:
  packages:
    - wget
    - vim
    - ufw
    - telnet
    - gcc
    - openssl
    - make
    - python-software-properties
    - software-properties-common
    - atop
