---
# Tasks file to install PHP and all its modules
- name: create a directory to download all required packages locally
  file:
    path: /var/cache/yum/local-packages
    state: directory

- name: Downloading current PHP version packages locally for future usage
  shell: yumdownloader {{ item }}
  args:
    chdir: /var/cache/yum/local-packages
  with_items: 
    - php56w
    - php56w-bcmath
    - php56w-common
    - php56w-cli
    - php56w-devel
    - php56w-gd
    - php56w-imap
    - php56w-mbstring
    - php56w-mcrypt
    - php56w-mysql
    - php56w-opcache
    - php56w-pdo
    - php56w-pear
    - php56w-pecl-memcache
    - php56w-process
    - php56w-soap
    - php56w-tidy
    - php56w-xml
    - php56w-xmlrpc 

- name: Install PHP and PHP modules
  yum: 
    name: "{{ item }}"
    state: present
  with_items: 
    - php56w
    - php56w-bcmath
    - php56w-common
    - php56w-cli
    - php56w-devel
    - php56w-gd
    - php56w-imap
    - php56w-mbstring
    - php56w-mcrypt
    - php56w-mysql
    - php56w-opcache
    - php56w-pdo
    - php56w-pear
    - php56w-pecl-memcache
    - php56w-process
    - php56w-soap
    - php56w-tidy
    - php56w-xml
    - php56w-xmlrpc

- name: Write php.info file in apache document root
  copy:
    src: phpinfo.php
    dest: /var/www/html/phpinfo.php  

- name: Modify php.ini file with the default we use
  template:
    src: php.ini.j2
    dest: /etc/php.ini
  notify:
    - Restart Apache on RedHat OS
