---
# handlers file for apache_installation
- name: Restart Apache on RedHat OS
  systemd:
    name: httpd
    state: restarted

- name: Restarting Apache on Debian OS
  service: name=apache2 state=restarted

- name: Restarting firewalld
  systemd:
    name: firewalld
    state: reloaded
