---
#default variables for galera installation role
wsrep_on: ON
wsrep_provider: "/usr/lib64/galera/libgalera_smm.so"
wsrep_cluster_name: "Galera Cluster"
wsrep_sst_method: rsync
wsrep_slave_threads: 10
wsrep_provider_options: "gcache.size=2G;gcache.page_size=1G;gcs.fc_limit=256;gcs.fc_factor=0.99;"
wsrep_certify_nonPK: 1
wsrep_max_ws_rows: 131072
wsrep_max_ws_size: 1073741824
wsrep_debug: 1
wsrep_convert_LOCK_to_trx: 0
wsrep_retry_autocommit: 1
wsrep_auto_increment_control: 1
wsrep_drupal_282555_workaround: 0
wsrep_causal_reads: 0

