---
# handlers file for apache_installation
- name: Restart Apache on RedHat OS
  systemd:
    name: httpd
    state: restarted

- name: Restart Apache on Debian OS
  service: name=apache2 state=restarted
