---
- block:
    - name: Installing MariaDB Packages
      yum: 
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - MariaDB-server 
        - MariaDB-client
        - xinetd
 
    - name: create temp directory for mysql slow query in memory cache
      file: 
        group: mysql
        mode: 0755
        owner: mysql
        path: "{{ mysql_tmp_store }}"
        state: directory

    - name: Changing Mariadb Configration Settings
      template:
        src: mariadb.j2
        dest: /etc/my.cnf.d/performance_settings.cnf
        owner: mysql
        group: mysql
        mode: 0644
      notify:
        - restart mariadb

    - name: Allow MySQL port in firewalld
      firewalld:
        port: 3306/tcp
        permanent: true
        state: enabled
      notify: reload firewalld

    - name: Starting MariaDB service
      systemd:
        name: mariadb
        state: started
        enabled: yes
      register: _svc_mariadb
    
    - name: Chaning Root Password for MariaDB
      command: mysqladmin -u root password {{ mariadb_root_password }}
      when: _svc_mariadb.changed == True
  tags:
    - mariadb_install
    - redhat_mariadb_install
