---
# tasks file for interface_add
#- name: generating random routing table number
#  set_fact:
#     table_num: "{{ 100 | random(start=20) }}"
#  run_once: yes
#
#- name: generating randome priority for route
#  set_fact:
#     priority: "{{ 500 | random(start=100) }}"
#  run_once: yes
#
#- name: printing random routing table number
#  debug: var=table_num
#
#- name: printing random routing table number
#  debug: var=priority
#
#- name: eth0 interface address
#  debug:
#    var:  hostvars[inventory_hostname]['ansible_%s'| format(item)]['ipv4']['address']
#  with_items: "{{ ansible_interfaces[1:] }}"
#  when:
#    - item == 'eth0'

- name: generating random routing table number
  set_fact:
     table_num: "{{ 100 | random(start=20) }}"
  run_once: yes

- name: generating randome priority for route
  set_fact:
     priority: "{{ 500 | random(start=100) }}"
  run_once: yes

- name: creating route entries for nic interface
  template:
    src: route.j2
    dest: /etc/sysconfig/network-scripts/route-{{ item }}
  with_items: "{{ ansible_interfaces[1:] }}"
  when:
    - item == 'eth0'

- name: creating rule table for nic interface
  template:
    src: rule.j2
    dest: /etc/sysconfig/network-scripts/rule-{{ item }}
  with_items: "{{ ansible_interfaces[1:] }}"
  when:
    - item == 'eth0'
