---
# defaults file for netdata_installation
debian:
  packages:
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - gcc
    - git
    - libmnl-dev
    - make
    - pkg-config
    - uuid-dev
    - zlib1g-dev

redhat:
  packages:
    - autoconf
    - autogen
    - automake
    - openssl
    - openssl-devel
    - curl
    - git
    - jq
    - libmnl-devel
    - libuuid-devel
    - zlib-devel
    - gcc
    - make
    - pkgconfig
