---
# defaults file for netdata_installation
debian:
  packages:
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - gcc
    - git
    - libmnl-dev
    - make
    - pkg-config
    - uuid-dev
    - zlib1g-dev

redhat:
  packages:
    - autoconf
    - autoconf-archive
    - autogen
    - automake
    - openssl
    - openssl-devel
    - curl
    - gcc
    - git
    - jq
    - libtool
    - libmnl-devel
    - libuuid-devel
    - make
    - pkgconfig
    - zlib-devel
    - python-twisted-core
    - python-zope-interface
    - desktop-file-utils
    - groff
    - graphviz
    - selinux-policy-devel
    - libcap-ng-devel
    - python-devel
    - PyYAML
