---
# tasks file for debug_run

#- name: debug groups
#  debug: 
#    msg: "{{ groups['dbservers'] }}"
#
#- name: debug hostvars
#  debug: 
#    var: "{{ hostvars['dbserver-1']['ansible_{{ galera_interface }}']['ipv4']['address'] }}"

#- debug: var=hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address']
#- debug: var=play_hosts
#- debug: var=inventory_hostname
#- debug: var=hostvars[inventory_hostname]
- name: making db hosts enteries in /etc/hosts
  template:
    src: gcom.j2
    dest: /tmp/hosts
