---
#Playbook to setup galera replication on existing mariadb installed servers
- name: Play to setup galera replication on mariadb installed servers
  hosts: galera-cluster
  become: yes
  roles:
    - { role: galera-installation }
